name: controlvideo
channels:
  - xformers/label/dev
  - pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hecacb30_2
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - numpy=1.24.3=py39h14f4228_0
  - numpy-base=1.24.3=py39h31eccc5_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.8=h7f8727e_0
  - pip=23.0.1=py39h06a4308_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h955ad1f_3
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=67.8.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py39_cu116
  - torchvision=0.13.1=py39_cu116
  - typing_extensions=4.6.3=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=2.0.3=pyhd8ed1ab_0
  - wheel=0.38.4=py39h06a4308_0
  - xformers=0.0.21.dev547+git.2cc77ae=py39_cu11.6.2_pyt1.12.1
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - accelerate==0.12.0
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - attrs==23.1.0
    - click==8.1.3
    - cmake==3.26.3
    - contextlib2==21.6.0
    - contourpy==1.0.7
    - cycler==0.11.0
    - decord==0.6.0
    - diffusers==0.11.1
    - docker-pycreds==0.4.0
    - einops==0.6.1
    - filelock==3.12.0
    - fonttools==4.39.4
    - fsspec==2023.5.0
    - ftfy==6.1.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - huggingface-hub==0.14.1
    - imageio==2.31.0
    - imageio-ffmpeg==0.4.8
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - jsonlines==3.1.0
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - lit==16.0.5.post0
    - matplotlib==3.7.1
    - ml-collections==0.1.1
    - networkx==3.1
    - omegaconf==2.3.0
    - opencv-python==4.7.0.72
    - packaging==23.1
    - pathtools==0.1.2
    - pillow==9.5.0
    - protobuf==4.23.2
    - psutil==5.9.5
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pywavelets==1.4.1
    - pyyaml==6.0
    - regex==2023.5.5
    - scikit-image==0.21.0
    - scipy==1.10.1
    - sentry-sdk==1.25.0
    - setproctitle==1.3.2
    - smmap==5.0.0
    - tifffile==2023.4.12
    - timm==0.4.9
    - tokenizers==0.13.3
    - tqdm==4.65.0
    - transformers==4.23.1
    - triton==2.0.0.post1
    - wandb==0.15.4
    - wcwidth==0.2.6
    - zipp==3.15.0
prefix: /workspace/home/zhaomin/anaconda3/envs/controlvideo
